name: Publish package to GitHub Packages
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: build
        run: |
          cd ./server 
          npm install
          npm run build --if-present
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "server_${{github.ref_name}}_${{ steps.date.outputs.date }}"
          path: |
            server/dist