name: Publish package to GitHub Packages
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: change directory
        run: cd ./server 
      - name: build
        run: |
          npm install
          npm run build --if-present
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: server-artifact
          path: |
            dist
            !dist/**/*.md